<?php
$dalTableEoc_chigins2 = array();
$dalTableEoc_chigins2["chigin_id"] = array("type"=>3,"varname"=>"chigin_id");
$dalTableEoc_chigins2["chigin_ecc_id"] = array("type"=>3,"varname"=>"chigin_ecc_id");
$dalTableEoc_chigins2["MATERIAL"] = array("type"=>200,"varname"=>"MATERIAL");
$dalTableEoc_chigins2["ITEM"] = array("type"=>200,"varname"=>"ITEM");
$dalTableEoc_chigins2["remark"] = array("type"=>201,"varname"=>"remark");
$dalTableEoc_chigins2["WEIGHT"] = array("type"=>200,"varname"=>"WEIGHT");
$dalTableEoc_chigins2["PER_PRICE"] = array("type"=>200,"varname"=>"PER_PRICE");
$dalTableEoc_chigins2["AMOUNT_MONEY"] = array("type"=>200,"varname"=>"AMOUNT_MONEY");
$dalTableEoc_chigins2["gram"] = array("type"=>200,"varname"=>"gram");
$dalTableEoc_chigins2["eq"] = array("type"=>200,"varname"=>"eq");
$dalTableEoc_chigins2["eq2"] = array("type"=>200,"varname"=>"eq2");
$dalTableEoc_chigins2["twice"] = array("type"=>200,"varname"=>"twice");
$dalTableEoc_chigins2["en"] = array("type"=>200,"varname"=>"en");
$dalTableEoc_chigins2["en2"] = array("type"=>200,"varname"=>"en2");
$dalTableEoc_chigins2["create_at"] = array("type"=>135,"varname"=>"create_at");
$dalTableEoc_chigins2["_status"] = array("type"=>3,"varname"=>"_status");
$dalTableEoc_chigins2["updated_by"] = array("type"=>3,"varname"=>"updated_by");
$dalTableEoc_chigins2["created_by"] = array("type"=>3,"varname"=>"created_by");
$dalTableEoc_chigins2["update_at"] = array("type"=>135,"varname"=>"update_at");
$dalTableEoc_chigins2["label_output_flag"] = array("type"=>3,"varname"=>"label_output_flag");
$dalTableEoc_chigins2["product_num"] = array("type"=>3,"varname"=>"product_num");
$dalTableEoc_chigins2["category_id"] = array("type"=>3,"varname"=>"category_id");
$dalTableEoc_chigins2["sub_category_id1"] = array("type"=>3,"varname"=>"sub_category_id1");
$dalTableEoc_chigins2["yahoo_sex"] = array("type"=>3,"varname"=>"yahoo_sex");
$dalTableEoc_chigins2["line"] = array("type"=>200,"varname"=>"line");
$dalTableEoc_chigins2["item_name"] = array("type"=>200,"varname"=>"item_name");
$dalTableEoc_chigins2["motif"] = array("type"=>200,"varname"=>"motif");
$dalTableEoc_chigins2["product_id"] = array("type"=>3,"varname"=>"product_id");
$dalTableEoc_chigins2["status"] = array("type"=>3,"varname"=>"status");
$dalTableEoc_chigins2["serial_number"] = array("type"=>200,"varname"=>"serial_number");
$dalTableEoc_chigins2["yahoo_kataban"] = array("type"=>200,"varname"=>"yahoo_kataban");
$dalTableEoc_chigins2["stamp"] = array("type"=>200,"varname"=>"stamp");
$dalTableEoc_chigins2["Setting"] = array("type"=>200,"varname"=>"Setting");
$dalTableEoc_chigins2["Destination_selling"] = array("type"=>200,"varname"=>"Destination_selling");
$dalTableEoc_chigins2["Finish"] = array("type"=>200,"varname"=>"Finish");
$dalTableEoc_chigins2["Discrimination"] = array("type"=>200,"varname"=>"Discrimination");
$dalTableEoc_chigins2["accessories"] = array("type"=>200,"varname"=>"accessories");
$dalTableEoc_chigins2["yahoo_sankou_uwadai"] = array("type"=>200,"varname"=>"yahoo_sankou_uwadai");
$dalTableEoc_chigins2["sales_price"] = array("type"=>5,"varname"=>"sales_price");
	$dalTableEoc_chigins2["chigin_id"]["key"]=true;

$dal_info["internet_at_urlounge_co_jp__Eoc_chigins2"] = &$dalTableEoc_chigins2;
?>