
Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button1';if(!pageObj.buttonEventBefore['New_Button1']){pageObj.buttonEventBefore['New_Button1']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button1']){pageObj.buttonEventAfter['New_Button1']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button1"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button1"+"_"+Runner.genId();var button_New_Button1=new Runner.form.Button({id:this.id,btnName:"New_Button1"});button_New_Button1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button2';if(!pageObj.buttonEventBefore['New_Button2']){pageObj.buttonEventBefore['New_Button2']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button2']){pageObj.buttonEventAfter['New_Button2']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button2"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button2"+"_"+Runner.genId();var button_New_Button2=new Runner.form.Button({id:this.id,btnName:"New_Button2"});button_New_Button2.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button3';if(!pageObj.buttonEventBefore['New_Button3']){pageObj.buttonEventBefore['New_Button3']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){if(confirm('一括登録しますか'))
return true;else
return false;params["txt"]="START BATCH EXCUTE";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button3']){pageObj.buttonEventAfter['New_Button3']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button3"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button3"+"_"+Runner.genId();var button_New_Button3=new Runner.form.Button({id:this.id,btnName:"New_Button3"});button_New_Button3.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button4';if(!pageObj.buttonEventBefore['New_Button4']){pageObj.buttonEventBefore['New_Button4']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button4']){pageObj.buttonEventAfter['New_Button4']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button4"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button4"+"_"+Runner.genId();var button_New_Button4=new Runner.form.Button({id:this.id,btnName:"New_Button4"});button_New_Button4.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button5';if(!pageObj.buttonEventBefore['New_Button5']){pageObj.buttonEventBefore['New_Button5']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button5']){pageObj.buttonEventAfter['New_Button5']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button5"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button5"+"_"+Runner.genId();var button_New_Button5=new Runner.form.Button({id:this.id,btnName:"New_Button5"});button_New_Button5.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button6';if(!pageObj.buttonEventBefore['New_Button6']){pageObj.buttonEventBefore['New_Button6']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button6']){pageObj.buttonEventAfter['New_Button6']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button6"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button6"+"_"+Runner.genId();var button_New_Button6=new Runner.form.Button({id:this.id,btnName:"New_Button6"});button_New_Button6.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button7';if(!pageObj.buttonEventBefore['New_Button7']){pageObj.buttonEventBefore['New_Button7']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button7']){pageObj.buttonEventAfter['New_Button7']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button7"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button7"+"_"+Runner.genId();var button_New_Button7=new Runner.form.Button({id:this.id,btnName:"New_Button7"});button_New_Button7.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button8';if(!pageObj.buttonEventBefore['New_Button8']){pageObj.buttonEventBefore['New_Button8']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){if(confirm('一括更新しますか？?'))
return true;else
return false;params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button8']){pageObj.buttonEventAfter['New_Button8']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button8"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button8"+"_"+Runner.genId();var button_New_Button8=new Runner.form.Button({id:this.id,btnName:"New_Button8"});button_New_Button8.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button9';if(!pageObj.buttonEventBefore['New_Button9']){pageObj.buttonEventBefore['New_Button9']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button9']){pageObj.buttonEventAfter['New_Button9']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button9"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button9"+"_"+Runner.genId();var button_New_Button9=new Runner.form.Button({id:this.id,btnName:"New_Button9"});button_New_Button9.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button10';if(!pageObj.buttonEventBefore['New_Button10']){pageObj.buttonEventBefore['New_Button10']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){if(confirm('一括更新しますか？?'))
return true;else
return false;params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button10']){pageObj.buttonEventAfter['New_Button10']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button10"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button10"+"_"+Runner.genId();var button_New_Button10=new Runner.form.Button({id:this.id,btnName:"New_Button10"});button_New_Button10.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button11';if(!pageObj.buttonEventBefore['New_Button11']){pageObj.buttonEventBefore['New_Button11']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button11']){pageObj.buttonEventAfter['New_Button11']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button11"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button11"+"_"+Runner.genId();var button_New_Button11=new Runner.form.Button({id:this.id,btnName:"New_Button11"});button_New_Button11.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button12';if(!pageObj.buttonEventBefore['New_Button12']){pageObj.buttonEventBefore['New_Button12']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){if(confirm('ステータスを一括変更しますか？?'))
return true;else
return false;params["txt"]="変更開始";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button12']){pageObj.buttonEventAfter['New_Button12']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 変更終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button12"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button12"+"_"+Runner.genId();var button_New_Button12=new Runner.form.Button({id:this.id,btnName:"New_Button12"});button_New_Button12.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button15';if(!pageObj.buttonEventBefore['New_Button15']){pageObj.buttonEventBefore['New_Button15']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="更新";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button15']){pageObj.buttonEventAfter['New_Button15']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button15"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button15"+"_"+Runner.genId();var button_New_Button15=new Runner.form.Button({id:this.id,btnName:"New_Button15"});button_New_Button15.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button16';if(!pageObj.buttonEventBefore['New_Button16']){pageObj.buttonEventBefore['New_Button16']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button16']){pageObj.buttonEventAfter['New_Button16']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button16"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button16"+"_"+Runner.genId();var button_New_Button16=new Runner.form.Button({id:this.id,btnName:"New_Button16"});button_New_Button16.init({args:[pageObj,proxy,pageid]});});});