
Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button14';if(!pageObj.buttonEventBefore['New_Button14']){pageObj.buttonEventBefore['New_Button14']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button14']){pageObj.buttonEventAfter['New_Button14']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button14"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button14"+"_"+Runner.genId();var button_New_Button14=new Runner.form.Button({id:this.id,btnName:"New_Button14"});button_New_Button14.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button41';if(!pageObj.buttonEventBefore['New_Button41']){pageObj.buttonEventBefore['New_Button41']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="品番買取額設定開始";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button41']){pageObj.buttonEventAfter['New_Button41']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){function On(result,ctrl)
{}}
$('a[id="New_Button41"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button41"+"_"+Runner.genId();var button_New_Button41=new Runner.form.Button({id:this.id,btnName:"New_Button41"});button_New_Button41.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button51';if(!pageObj.buttonEventBefore['New_Button51']){pageObj.buttonEventBefore['New_Button51']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="品番販売額";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button51']){pageObj.buttonEventAfter['New_Button51']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button51"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button51"+"_"+Runner.genId();var button_New_Button51=new Runner.form.Button({id:this.id,btnName:"New_Button51"});button_New_Button51.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button31';if(!pageObj.buttonEventBefore['New_Button31']){pageObj.buttonEventBefore['New_Button31']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){if(confirm('一括登録しますか'))
return true;else
return false;params["txt"]="START BATCH EXCUTE";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button31']){pageObj.buttonEventAfter['New_Button31']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){function On(result,ctrl)
{}}
$('a[id="New_Button31"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button31"+"_"+Runner.genId();var button_New_Button31=new Runner.form.Button({id:this.id,btnName:"New_Button31"});button_New_Button31.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button21';if(!pageObj.buttonEventBefore['New_Button21']){pageObj.buttonEventBefore['New_Button21']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button21']){pageObj.buttonEventAfter['New_Button21']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button21"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button21"+"_"+Runner.genId();var button_New_Button21=new Runner.form.Button({id:this.id,btnName:"New_Button21"});button_New_Button21.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button61';if(!pageObj.buttonEventBefore['New_Button61']){pageObj.buttonEventBefore['New_Button61']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button61']){pageObj.buttonEventAfter['New_Button61']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button61"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button61"+"_"+Runner.genId();var button_New_Button61=new Runner.form.Button({id:this.id,btnName:"New_Button61"});button_New_Button61.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button71';if(!pageObj.buttonEventBefore['New_Button71']){pageObj.buttonEventBefore['New_Button71']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button71']){pageObj.buttonEventAfter['New_Button71']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button71"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button71"+"_"+Runner.genId();var button_New_Button71=new Runner.form.Button({id:this.id,btnName:"New_Button71"});button_New_Button71.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button81';if(!pageObj.buttonEventBefore['New_Button81']){pageObj.buttonEventBefore['New_Button81']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){if(confirm('一括更新しますか？?'))
return true;else
return false;params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button81']){pageObj.buttonEventAfter['New_Button81']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button81"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button81"+"_"+Runner.genId();var button_New_Button81=new Runner.form.Button({id:this.id,btnName:"New_Button81"});button_New_Button81.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button91';if(!pageObj.buttonEventBefore['New_Button91']){pageObj.buttonEventBefore['New_Button91']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button91']){pageObj.buttonEventAfter['New_Button91']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button91"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button91"+"_"+Runner.genId();var button_New_Button91=new Runner.form.Button({id:this.id,btnName:"New_Button91"});button_New_Button91.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button101';if(!pageObj.buttonEventBefore['New_Button101']){pageObj.buttonEventBefore['New_Button101']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){if(confirm('一括更新しますか？?'))
return true;else
return false;params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button101']){pageObj.buttonEventAfter['New_Button101']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);}}
$('a[id="New_Button101"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button101"+"_"+Runner.genId();var button_New_Button101=new Runner.form.Button({id:this.id,btnName:"New_Button101"});button_New_Button101.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button111';if(!pageObj.buttonEventBefore['New_Button111']){pageObj.buttonEventBefore['New_Button111']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button111']){pageObj.buttonEventAfter['New_Button111']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 設定終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button111"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button111"+"_"+Runner.genId();var button_New_Button111=new Runner.form.Button({id:this.id,btnName:"New_Button111"});button_New_Button111.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button121';if(!pageObj.buttonEventBefore['New_Button121']){pageObj.buttonEventBefore['New_Button121']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){if(confirm('ステータスを一括変更しますか？?'))
return true;else
return false;params["txt"]="変更開始";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button121']){pageObj.buttonEventAfter['New_Button121']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" 変更終了!!!";ctrl.setMessage(message);location.reload();}}
$('a[id="New_Button121"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button121"+"_"+Runner.genId();var button_New_Button121=new Runner.form.Button({id:this.id,btnName:"New_Button121"});button_New_Button121.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button17';if(!pageObj.buttonEventBefore['New_Button17']){pageObj.buttonEventBefore['New_Button17']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="更新";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button17']){pageObj.buttonEventAfter['New_Button17']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button17"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button17"+"_"+Runner.genId();var button_New_Button17=new Runner.form.Button({id:this.id,btnName:"New_Button17"});button_New_Button17.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('store_products_batch_shinaban',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button18';if(!pageObj.buttonEventBefore['New_Button18']){pageObj.buttonEventBefore['New_Button18']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['New_Button18']){pageObj.buttonEventAfter['New_Button18']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="New_Button18"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="New_Button18"+"_"+Runner.genId();var button_New_Button18=new Runner.form.Button({id:this.id,btnName:"New_Button18"});button_New_Button18.init({args:[pageObj,proxy,pageid]});});});